In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\iamha\Downloads\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [4]:
#remove duplicates
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [5]:
#striping off unwanted characters
df["Last_Name"] = df["Last_Name"].str.strip("123./_")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [10]:
#reformatting phone numbers into a single format
# df["Phone_Number"] = df["Phone_Number"].str.replace("[^a-zA-Z0-9]", "", regex=True)
# df["Phone_Number"]
# df["Phone_Number"] = df["Phone_Number"].apply(lambda x: str(x))
# df["Phone_Number"]
# df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3] + "-" + x[3:6] + "-" + x[6:10])
df["Phone_Number"] = df["Phone_Number"].replace("nan--", "")
df["Phone_Number"] = df["Phone_Number"].replace("Na--", "")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [13]:
df[["Street_Address", "State", "Zip_Code"]] = df["Address"].str.split(",",n=2, expand=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None

In [15]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,White,,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,True,910 Tatooine Road,Tatooine,None

In [20]:
# df["Paying Customer"] = df["Paying Customer"].str.replace("Yes", "Y")
# df["Paying Customer"] = df["Paying Customer"].str.replace("No", "N")
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace("Yes", "Y")
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace("No", "N")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code,Paying Customer\t
0,1001,Frodo,Baggins,123-545-5421,Y,N,True,123 Shire Lane,Shire,None,Yeses
1,1002,Abed,Nadir,123-643-9775,N,Y,False,93 West Main Street,None,None,No
2,1003,Walter,White,,N,NaN,True,298 Drugs Driveway,None,None,N
3,1004,Dwight,Schrute,123-543-2345,Y,Y,True,980 Paper Avenue,Pennsylvania,18503,Yeses
4,1005,Jon,Snow,876-678-3469,Y,N,True,123 Dragons Road,None,None,Yes
5,1006,Ron,Swanson,304-762-2467,Y,Y,True,768 City Parkway,None,None,Yeses
6,1007,Jeff,Winger,,N,N,False,1209 South Street,None,None,No
7,1008,Sherlock,Holmes,876-678-3469,N,N,False,98 Clue Drive,None,None,N
8,1009,Gandalf,NaN,,Y,NaN,False,123 Middle Earth,None,None,Yeses
9,1010,Peter,Parker,123-545-5421,Y,N,True,25th Main Street,New York,None,Yeses
10,1011,Samwise,Gamgee,,Y,N,True,612 Shire Lane,Shire,None,Yeses
11,1012,Harry,Potter,,Y,NaN,True,2394 Hogwarts Avenue,None,None,Yes
12,1013,Don,Draper,123-543-2345,Y,N,False,2039 Main Street,None,None,Yeses
13,1014,Leslie,Knope,876-678-3469,Y,N,False,343 City Parkway,None,None,Yeses
14,1015,Toby,Flenderson,304-762-2467,N,N,False,214 HR Avenue,None,None,N
15,1016,Ron,Weasley,123-545-5421,N,N,False,2395 Hogwarts Avenue,None,None,No
16,1017,Michael,Scott,123-643-9775,Y,N,False,121 Paper Avenue,Pennsylvania,None,Yeses
17,1018,Clark,Kent,,Y,NaN,True,3498 Super Lane,None,None,Yes
18,1019,Creed,Braton,,N/a,Y,True,N/a,None,None,N/a
19,1020,Anakin,Skywalker,876-678-3469,Y,N,True,910 Tatooine Road,Tatooine,None,Yeses

In [28]:
df=df.drop(columns="Not_Useful_Column")

In [29]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code,Paying Customer\t
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,None,Yeses
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,None,None,No
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,None,None,N
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503,Yeses
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,None,None,Yes
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,None,None,Yeses
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None,No
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,None,None,N
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,None,None,Yeses
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,None,Yeses
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None,Yeses
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,None,None,Yes
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,None,None,Yeses
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,None,None,Yeses
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,None,None,N
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,None,None,No
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,None,Yeses
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None,Yes
18,1019,Creed,Braton,,N/a,Y,N/a,None,None,N/a
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,None,Yeses

In [30]:
df = df.fillna("")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code,Paying Customer\t
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,,Yeses
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,,,No
2,1003,Walter,White,,N,,298 Drugs Driveway,,,N
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503,Yeses
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,,Yes
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,,,Yeses
6,1007,Jeff,Winger,,N,N,1209 South Street,,,No
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,,N
8,1009,Gandalf,,,Y,,123 Middle Earth,,,Yeses
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,,Yeses
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,,Yeses
11,1012,Harry,Potter,,Y,,2394 Hogwarts Avenue,,,Yes
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,,Yeses
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,,Yeses
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,,N
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,,No
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,,Yeses
17,1018,Clark,Kent,,Y,,3498 Super Lane,,,Yes
18,1019,Creed,Braton,,N/a,Y,N/a,,,N/a
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,,Yeses

In [31]:
df=df.drop(columns="Paying Customer\t")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,,
2,1003,Walter,White,,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,N/a,Y,N/a,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [34]:
for i in df.index:
    if df.loc[i, "Do_Not_Contact"] == "Y" or df.loc[i, "Phone_Number"] == "":
        df.drop(i, inplace=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [36]:
df = df.reset_index(drop=True)

In [37]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
1,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
2,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
3,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
4,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
5,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
6,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
7,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
8,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
9,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,